spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/inventory
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      encoding: UTF-8
      mode: always
logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
